/*** HELP START ***//*

### Macro:

%kaplan_meier_plot

### Purpose:

Creates Kaplan-Meier survival plots using `PROC LIFETEST` and `PROC SGPLOT`.
The macro displays survival curves by group, censoring marks, and the number of
subjects at risk at specified time points.

### Parameters:

#### Input data and grouping

- `data` (optional, default=`dummy_adtte`) :
	Input time-to-event analysis dataset.

- `groupn` (optional, default=`TRTPN`) :
	Numeric grouping variable used to define the survival curves.

- `groupc` (optional, default=`TRTP`) :
	Character variable containing the display label for each group.

- `wh` (optional, default=blank) :
	WHERE condition used to subset the input dataset.

#### Time-to-event variables

- `Time_var` (optional, default=`AVAL`) :
	Numeric time-to-event analysis variable.

- `Censor_var` (optional, default=blank) :
	Censoring indicator variable.

- `Censor_val` (optional, default=blank) :
	Value of `Censor_var` that identifies censored observations.

- `Censore_var` (deprecated, default=`CNSR`) :
	Previous name of `Censor_var`, retained for backward compatibility. It is
	used only when `Censor_var` is blank.

- `Censore_val` (deprecated, default=`1`) :
	Previous name of `Censor_val`, retained for backward compatibility. It is
	used only when `Censor_val` is blank.

#### Titles, axes, and style

- `Title` (optional, default=`Kaplan-Meier Plot`) :
	Title displayed above the plot.

- `Group_color_list` (optional, default=`black black black black`) :
	Space-separated list of colors used for the group survival curves.

- `Group_linepattern_list` (optional, default=`solid shortdash longdash dash`) :
	Space-separated list of line patterns used for the group survival curves.

- `XLABEL` (optional, default=`Survival Time (Month)`) :
	Label displayed on the X-axis.

- `YLABEL` (optional, default=`Probability of Survival`) :
	Label displayed on the Y-axis.

- `AxisValues` (optional, default=`0 to 16 by 2`) :
	X-axis tick specification and time points used for the number-at-risk table.

#### Code generation

- `Generate_Code` (optional, default=`Y`) :
	When set to `Y`, generates the expanded SAS program code and writes it to a
	text file in the WORK directory.

### Example

~~~sas
%kaplan_meier_plot(
	data                   = dummy_adtte,
	groupn                 = TRTPN,
	groupc                 = TRTP,
	Time_var               = AVAL,
	Censor_var             = CNSR,
	Censor_val             = 1,
	Title                  = %nrbquote(Kaplan-Meier Curve Example),
	Group_color_list       = %nrbquote(black red blue green),
	Group_linepattern_list = %nrbquote(solid dash longdash shortdash),
	XLABEL                 = %nrbquote(Survival Time (Month)),
	YLABEL                 = %nrbquote(Probability),
	AxisValues             = %nrbquote(0 to 24 by 4),
	Generate_Code          = Y
);
~~~

### Output:

- Kaplan-Meier survival plot generated by ODS Graphics
- Number-at-risk table displayed below the survival curves
- Intermediate datasets including `SurvivalPlotData`, `Stratum`, `tAtRisk`,
  `atrisk`, and `SurvivalPlotData_1`
- `kaplan_meier_plot<index>.txt`: generated SAS code when `Generate_Code=Y`

### Prerequisites

- SAS/STAT with `PROC LIFETEST`
- An input dataset containing:
	- The grouping variables specified in `groupn` and `groupc`
	- The time-to-event variable specified in `Time_var`
	- The censoring variable specified in `Censor_var`

### Change history

- 2025-06-24: First release
- 2025-09-01: Bug fix
- 2025-09-16: Minor change
- 2026-02-05: Fixed generated-code output
- 2026-02-23: Renamed `Censore_var` and `Censore_val` to `Censor_var` and
  `Censor_val`
- 2026-04-03: Removed `ODS GRAPHICS RESET`
- 2026-07-30: Updated program header to markdown

### Author

Yutaka Morioka

*//*** HELP END ***/

%macro kaplan_meier_plot(
data = dummy_adtte ,
groupn = TRTPN ,
groupc = TRTP ,
wh = ,
Time_var = AVAL ,
Censor_var = ,
Censor_val = ,
Censore_var = CNSR ,
Censore_val = 1,
Title = %nrbquote(Kaplan-Meier Plot),
Group_color_list =%nrbquote(black black black black),
Group_linepattern_list =%nrbquote(solid shortdash longdash dash),
XLABEL =%nrbquote( Survival Time (Month)),
YLABEL =%nrbquote( Probability of Survival),
AxisValues =%nrbquote (0 to 16 by 2),
Generate_Code =Y
);

/* Backward compatibility: use old params only when new ones are not provided */
%if %superq(Censor_var) = %str() and %superq(Censore_var) ne %str() %then %do;
  %let Censor_var = &Censore_var;
%end;

%if %superq(Censor_val) = %str() and %superq(Censore_val) ne %str() %then %do;
  %let Censor_val = &Censore_val;
%end;

%let codepath = %sysfunc(pathname(WORK));
%put &codepath;
options nomfile;
%if %upcase(&Generate_Code) =Y %then %do;
%let sysind =&sysindex;
filename mprint "&codepath./kaplan_meier_plot&sysind..txt";
options mfile mprint;
%end;
data dummy_adtte;
attrib
USUBJID label="Unique Subject Identifier" length=$20.
TRTP  label="Planned Treatment" length=$20.
TRTPN	label="Planned Treatment (N)" length=8.
PARAM  label="Parameter" length=$50.
PARAMCD label="Parameter Code" length=$20.
PARAMN  label="Parameter (N)" length=8.
AVAL  label="Analysis Value" length=8.
CNSR  label="Censor" length=8.
;
call streaminit(1982);
do TRTPN = 1 to 4;
do _USUBJID = 1 to 100;
do PARAMN = 1 to 1;
if TRTPN =1 then time =rand('WEIBULL', 1.5, 10);
else if TRTPN =2 then time =rand('WEIBULL', 1.5, 7);
else if TRTPN =3 then time =rand('WEIBULL', 1.5, 3);
else time =rand('WEIBULL', 1.5, 5);
USUBJID = cats(TRTPN,_USUBJID);
censor_limit = rand('UNIFORM') * 15;
CNSR = ^(time <= censor_limit);
AVAL = min(time, censor_limit);
TRTP = choosec(TRTPN,"XXXXX","YYYY","ZZZZZ","Placebo");
PARAMCD = choosec(PARAMN,"PFS");
PARAM = choosec(PARAMN,"Progression Free Survival (Months)");
output;
end;
end;
end;
keep USUBJID -- CNSR;
run;
proc sort data=&data.(keep=&groupn. &groupc.) out=group_fmt nodupkey;
by &groupn. &groupc.;
run;
data group_fmt;
set group_fmt;
FMTNAME = "$KM_GR";
START = cats(&groupn.);
LABEL = &groupc.;
run;
proc format cntlin=group_fmt;
run;
ods graphics on;
ods noresults;
ods select none;
ods output Survivalplot=SurvivalPlotData;
proc lifetest data=&data.
plots=survival(atrisk=&AxisValues.);
time &Time_var. * &Censor_var.(&Censor_val.);
strata &groupn. ;
run;
proc sort data=SurvivalPlotData(keep = Stratum) out=Stratum nodupkey;
by Stratum;
run;
proc sort data=SurvivalPlotData(keep = tAtRisk) out=tAtRisk nodupkey;
where ^missing(tAtRisk);
by tAtRisk;
run;
data atrisk;
set Stratum;
if _N_=1 then do;
declare hash h1(dataset:"SurvivalPlotData(keep=Stratum tAtRisk)");
h1.definekey("Stratum","tAtRisk");
h1.definedone();
end;
do i=1 to obs;
set tAtRisk nobs=obs point=i;
AtRisk=0;
if h1.check() ne  0 then  output;
end;
run;
data SurvivalPlotData_1;
set SurvivalPlotData atrisk;
if ^missing(Censored) then do;
tick_marks_upper = Censored + 0.02;
tick_marks_lower = Censored - 0.02;
end;
run;
ods results;
ods select all;
ods graphics /
noborder
noscale
imagefmt=png
width=745 px
height=510 px
				             attrpriority=none;
title "&Title";
proc sgplot data=SurvivalPlotData_1 noborder noautolegend ;
styleattrs datacontrastcolors=(&Group_color_list)
				       datalinepatterns=(&Group_linepattern_list)
;
step x=time y=survival / group=stratum name='step' lineattrs=(thickness=2);
scatter x=time y=censored /noerrorcaps yerrorupper=tick_marks_upper yerrorlower=tick_marks_lower errorbarattrs=(pattern=1 thickness=2)  markerattrs=(size=0) GROUP=stratum;
xaxistable atrisk / x=tatrisk class=stratum location=outside colorgroup=stratum valueattrs=(size=10 ) ;
keylegend 'step' / location=inside position=topright across=1 noborder  valueattrs=(size=10) exclude=("") ;
yaxis label="&YLABEL." min=0 values=(0 0.2 0.4 0.5 0.6 0.8 1.0 ) offsetmax=0.03;
xaxis label="&XLABEL."  values=(&AxisValues.)  offsetmin=0.04 ;
format stratum $KM_GR. ;
run;
title;
%if %upcase(&Generate_Code) =Y %then %do;
  %*-- Only for Windows system --*;
  %if %index(%upcase(&SYSSCP), WIN) > 0 %then %do;
    options noxwait noxsync;
  %end;
  options nomprint nomfile;
  filename mprint clear;
  data _null_;
    put "NOTE: Generated Program Code File: &codepath./kaplan_meier_plot&sysind..txt";
  	call sleep(1,1);
  run;

  %*-- Open file when use XCMD --*;
  %if %sysfunc(getoption(xcmd))=XCMD %then %sysexec "&codepath./kaplan_meier_plot&sysind..txt";
%end;
%mend;
