/*** HELP START ***//*

### Macro:

%spider_plot

### Purpose:

Creates a spider plot (subject profile plot) using `PROC SGPLOT`.
The macro draws a series line with markers for each subject across the specified
X and Y variables. Optional reference lines, subject categories, axis settings,
and generated SAS code output are supported.

A dummy input dataset is created within the macro for demonstration.

### Parameters:

#### Input data and variables

- `data` (optional, default=`dummy_spider`) :
	Input dataset.

- `xvar` (optional, default=`ADY`) :
	Variable displayed on the X-axis, such as analysis day.

- `yvar` (optional, default=`PCHG`) :
	Variable displayed on the Y-axis, such as percent change from baseline.

- `subject_var` (optional, default=`SUBJID`) :
	Subject identifier used as the `GROUP=` variable in the `SERIES` statement.

- `subject_category` (optional, default=`BOR`) :
	Category variable used with `GROUPLC=` and `GROUPMC=` to control the line and
	marker colors. Leave blank when category-based coloring is not required.

#### Axes and appearance

- `xaxis_label` (optional, default=`Days`) :
	Label displayed on the X-axis.

- `xaxis_values` (optional, default=`0 43 85 127 169 191 213 235`) :
	Value specification passed to `XAXIS VALUES=()`.

- `yaxis_label` (optional, default=`Change rate from baseline (%)`) :
	Label displayed on the Y-axis.

- `yaxis_values` (optional, default=`-100 -75 -50 -30 0 20 50 75 100`) :
	Value specification passed to `YAXIS VALUES=()`.

- `datacontrastcolors` (optional, default=`Blue Red Green Yellow`) :
	Space-separated color list passed to `STYLEATTRS DATACONTRASTCOLORS=()`.

- `refline_value` (optional, default=`0 20 -30`) :
	One or more Y-axis values at which horizontal reference lines are displayed.
	Leave blank to suppress reference lines.

- `curvelabel` (optional, default=`Y`) :
	When set to `Y`, displays curve labels on the subject series.

#### Code generation

- `Generate_Code` (optional, default=`N`) :
	When set to `Y`, generates the expanded SAS program code, writes it to a text
	file in the WORK directory, and opens the file when supported.

### Example

~~~sas
%spider_plot(
	data               = dummy_spider,
	xvar               = ADY,
	yvar               = PCHG,
	subject_var        = SUBJID,
	subject_category   = BOR,
	xaxis_label        = %nrbquote(Days),
	xaxis_values       = %nrbquote(0 43 85 127 169 191 213 235),
	yaxis_label        = %nrbquote(Change rate from baseline (%)),
	yaxis_values       = %nrbquote(-100 -75 -50 -30 0 20 50 75 100),
	datacontrastcolors = %nrbquote(Blue Red Green Yellow),
	refline_value      = 0 20 -30,
	curvelabel         = Y,
	Generate_Code      = N
);
~~~

### Output:

- Spider plot generated by ODS Graphics
- `WORK.dummy_spider`: demonstration dataset created within the macro
- `spider_plot<index>.txt`: generated SAS code when `Generate_Code=Y`

### Prerequisites

- SAS with ODS Graphics and `PROC SGPLOT`
- An input dataset containing:
	- The variables specified in `xvar` and `yvar`
	- The subject identifier specified in `subject_var`
	- The category variable specified in `subject_category`, when provided

### Change history

- 2026-02-09: First release
- 2026-07-30:  `ODS GRAPHICS RESET`, updated program header to markdown

### Author

Yutaka Morioka

*//*** HELP END ***/

%macro spider_plot(
data = dummy_spider,
xvar=ADY,
yvar=PCHG,
subject_var=SUBJID,
subject_category=BOR,
xaxis_label=%nrbquote(Days) ,
xaxis_values =%nrbquote (0 43 85 127 169 191 213 235),
yaxis_label=%nrbquote(Change rate from baseline (%)) ,
yaxis_values =%nrbquote(-100 -75 -50 -30  0 20 50 75 100),
datacontrastcolors=%nrbquote(Blue Red Green Yellow),
refline_value =0 20 -30,
curvelabel=Y,
Generate_Code =N
);
%let codepath = %sysfunc(pathname(WORK));
%put &codepath;
options nomfile;
%if %upcase(&Generate_Code) =Y %then %do;
  %let ind=&sysindex.;
  filename mprint "&codepath.\spider_plot&ind..txt";
  options mfile mprint;
%end;

filename mytemp temp;
data _null_;
file mytemp;
put"101810@0@0@Complete Response";
put"101810@43@-10@Complete Response";
put"101810@85@-60@Complete Response";
put"101810@127@-70@Complete Response";
put"101810@169@-88@Complete Response";
put"101810@191@-100@Complete Response";
put"103101@0@0@Progressive Disease";
put"103101@43@10@Progressive Disease";
put"103101@85@50@Progressive Disease";
put"103101@127@70@Progressive Disease";
put"103105@0@0@Progressive Disease";
put"103105@43@10@Progressive Disease";
put"103105@85@30@Progressive Disease";
put"103105@127@40@Progressive Disease";
put"103105@169@45@Progressive Disease";
put"103201@0@0@Partial Response";
put"103201@43@-10@Partial Response";
put"103201@85@-10@Partial Response";
put"103201@127@-30@Partial Response";
put"103201@169@-20@Partial Response";
put"103201@191@-40@Partial Response";
put"103205@0@0@Partial Response";
put"103205@43@-30@Partial Response";
put"103205@85@-40@Partial Response";
put"103205@127@-50@Partial Response";
put"103205@169@-55@Partial Response";
put"103205@191@-55@Partial Response";
put"103205@213@-40@Partial Response";
run;

data dummy_spider;
attrib SUBJID length=$8. ADY length=8. PCHG length=8. BOR length=$19.;
infile mytemp lrecl=3000  dlm='@' dsd;
input SUBJID ADY PCHG BOR ;
run;
filename mytemp clear;

ods graphics / noborder noscale
               width=700px height=400px imagefmt=png;
proc sgplot data=&data. noborder ;
 styleattrs datacontrastcolors=(&datacontrastcolors.);
 %if %length(&refline_value) ne 0 %then %do;refline &refline_value. / lineattrs=(pattern=shortdash);%end;
  series x=&xvar. y=&yvar. / group=&subject_var 
         %if %length(&subject_category.) ne 0 %then %do; grouplc=&subject_category. groupmc=&subject_category. %end;
         markers markerattrs=(symbol=circlefilled) 
         lineattrs=(thickness=2 pattern=solid) name='spider' 
         %if %upcase(&curvelabel) = Y %then %do;curvelabel %end;; 
   keylegend 'spider' / title='' noborder type=linecolor valueattrs=(size=10) 
         location=inside position=topright across=1 opaque;
  xaxis label="&xaxis_label." values=(&xaxis_values.);
  yaxis label="&yaxis_label." values=(&yaxis_values.) ;
run;

%if %upcase(&Generate_Code) =Y %then %do;
%*-- Only for Windows system --*;
%if %index(%upcase(&SYSSCP), WIN) > 0 %then %do;
options noxwait noxsync;
%end;
  options nomprint nomfile;
  filename mprint clear;
  data _null_;
  	call sleep(1,1);
  run;
%if %sysfunc(getoption(xcmd))=XCMD %then  %sysexec "&codepath.\spider_plot&ind..txt";
%end;
%mend spider_plot;
